name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ THIS WAS MISSING (IMPORTANT)
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Gitayush1
          outputs: dist/github-contribution-grid-snake.svg

      - name: Deploy Snake
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
